#!/bin/sh
#set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir 2>/dev/null)"
if [ "$?" = "0" ]; then
    trap 'rm -f "$dir/$$.tags"' EXIT
    git ls-files | \
        #ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
        ctags --tag-relative=yes -R -f "$dir/$$.tags" --languages=-javascript,sql
    mv "$dir/$$.tags" "$dir/tags"
else
    find . -type f | \
        ctags --tag-relative=yes -R -f ".tags" --languages=-javascript,sql
fi
